blank_issues_enabled: false
contact_links:
  - name: Community Discussions
    url: https://github.com/Venomous-Sound/bESTEEbROWSER-beta/discussions
    about: Please ask questions and discuss ideas here
  - name: Discord Community
    url: https://discord.gg/DdQAkUbdm8
    about: Join our Discord for real-time chat and support